<?php

if (function_exists('acf_register_block')) {

    acf_register_block([
        'name' => 'general-columns-block',
        'title' => __('General Columns Block'),
        'description' => __('Columns Block'),
        'render_callback' => 'renderACFBlock',
        'category' => 'layout',
        'icon' => 'admin-comments',
        'mode' => 'edit',
        'keywords' => ['columns', 'block', 'general'],
        'post_types' => ['post', 'page']
    ]);

    if (function_exists('acf_add_local_field_group')) {

        acf_add_local_field_group(array(
            'key' => 'general-columns-block',
            'title' => 'General Columns Block',
            'fields' => array(
                array(
                    'key' => 'general-columns-block-row',
                    'label' => 'Row',
                    'name' => 'rows',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '100',
                        'class' => '',
                        'id' => '',
                    ),
                    'acfe_repeater_stylised_button' => 0,
                    'collapsed' => '',
                    'min' => 0,
                    'max' => 0,
                    'layout' => 'block',
                    'button_label' => 'Add Row',
                    "sub_fields" => array(
                        array(
                            'key' => 'general-columns-block-column',
                            'label' => 'Column',
                            'name' => 'columns',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '100',
                                'class' => '',
                                'id' => '',
                            ),
                            'acfe_repeater_stylised_button' => 0,
                            'collapsed' => '',
                            'min' => 0,
                            'max' => 0,
                            'layout' => 'block',
                            'button_label' => 'Add Column',
                            "sub_fields" => array(
                                array(
                                    'key' => 'general-columns-block-gradient-color',
                                    'label' => 'Gradient Colour',
                                    'name' => 'gradient_colour',
                                    'type' => 'color_picker',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '50',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                ),
                                array(
                                    'key' => 'general-columns-block-gradient-direction',
                                    'label' => 'Gradient Direction',
                                    'name' => 'gradient_direction',
                                    'type' => 'select',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '50',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'choices' => array(
                                        '180deg' => 'Top to Bottom',
                                        '0deg' => 'Bottom to Top',
                                        '90deg' => 'Left to Right',
                                        '270deg' => 'Right to Left',
                                    ),
                                    'default_value' => '180deg',
                                    'allow_null' => 0,
                                    'multiple' => 0,
                                    'ui' => 0,
                                    'return_format' => 'value',
                                    'ajax' => 0,
                                    'placeholder' => '',
                                ),
                                array(
                                    'key' => 'general-columns-block-background-color',
                                    'label' => 'Background Colour',
                                    'name' => 'background_colour',
                                    'type' => 'color_picker',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '50',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                ),
                                array(
                                    'key' => 'general-columns-block-opacity',
                                    'label' => 'Background Opacity',
                                    'name' => 'background_opacity',
                                    'type' => 'select',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '50',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'choices' => array(
                                        '0.1' => '10%',
                                        '0.2' => '20%',
                                        '0.3' => '30%',
                                        '0.4' => '40%',
                                        '0.5' => '50%',
                                        '0.6' => '60%',
                                        '0.7' => '70%',
                                        '0.8' => '80%',
                                        '0.9' => '90%',
                                        '1' => '100%',
                                    ),
                                    'default_value' => '1',
                                    'allow_null' => 0,
                                    'multiple' => 0,
                                    'ui' => 0,
                                    'return_format' => 'value',
                                    'ajax' => 0,
                                    'placeholder' => '',
                                ),
                                array(
                                    'key' => 'general-columns-block-background-image',
                                    'label' => 'Background Image',
                                    'name' => 'background_image',
                                    'type' => 'image',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '100',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'return_format' => 'array',
                                    'preview_size' => 'medium',
                                    'library' => 'all',
                                    'min_width' => '',
                                    'min_height' => '',
                                    'min_size' => '',
                                    'max_width' => '',
                                    'max_height' => '',
                                    'max_size' => '',
                                    'mime_types' => '',
                                ),
                                array(
                                    'key' => 'field_column_text',
                                    'label' => 'Text',
                                    'name' => 'text',
                                    'type' => 'wysiwyg',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '100',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'tabs' => 'all',
                                    'toolbar' => 'full',
                                    'media_upload' => 0,
                                    'delay' => 0,
                                ),
                                array(
                                    'key' => 'field_column_button',
                                    'label' => 'Button',
                                    'name' => 'button',
                                    'type' => 'link',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '50',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'return_format' => 'array',
                                ),
                                array(
                                    'key' => 'field_column_button_position',
                                    'label' => 'Button Position',
                                    'name' => 'button_position',
                                    'type' => 'select',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '50',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'choices' => array(
                                        'left' => 'Left',
                                        'center' => 'Centre',
                                        'right' => 'Right',
                                    ),
                                    'default_value' => 'Centre',
                                    'allow_null' => 0,
                                    'multiple' => 0,
                                    'ui' => 0,
                                    'return_format' => 'value',
                                    'ajax' => 0,
                                    'placeholder' => '',
                                ),
                            )
                        ),
                    )
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'block',
                        'operator' => '==',
                        'value' => 'acf/general-columns-block',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'left',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'acfe_display_title' => '',
            'acfe_autosync' => '',
            'acfe_form' => 0,
            'acfe_meta' => '',
            'acfe_note' => '',
        ));
    }
}
