<?php

if (function_exists('acf_register_block')) {

    acf_register_block([
		'name' => 'people',
		'title' => __('People Block'),
		'description' => __('People Block'),
		'render_callback' => 'renderACFBlock',
		'category' => 'layout',
		'icon' => 'admin-comments',
		'mode' => 'preview',
		'keywords' => ['people', 'block'],
		'post_types' => ['post', 'page']
	]);

    if (function_exists('acf_add_local_field_group')) {

		acf_add_local_field_group(array(
			'key' => 'people-block',
			'title' => 'People Block',
			'fields' => array(
				array(
					'key' => 'people-block-background',
					'label' => 'Background',
					'name' => 'background',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'default_value' => '',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'people-block-background-image',
					'label' => 'Background Image',
					'name' => 'background_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'default_value' => '',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
                array(
                    'key' => 'people_block_carousel_speed',
                    'label' => 'Autoplay Carousel Speed',
                    'name' => 'carousel_speed',
                    'type' => 'text',
                    'instructions' => 'Enter number of seconds e.g. 1 or 1.5',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '3',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
				array(
					'key' => 'people-block-title',
					'label' => 'Title',
					'name' => 'title',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'default_value' => '',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'people-block-people',
					'label' => 'People',
					'name' => 'people',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'default_value' => '',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
                    'sub_fields' => array(
                        array(
                            'key' => 'people-block-image',
                            'label' => 'Image',
                            'name' => 'image',
                            'type' => 'image',
                            'required' => 1,
							'wrapper' => array(
								'width' => '30',
								'class' => '',
								'id' => '',
							),
                        ),
                        array(
                            'key' => 'people-block-name',
                            'label' => 'Name',
                            'name' => 'name',
                            'type' => 'wysiwyg',
                            'required' => true,
							'wrapper' => array(
								'width' => '30',
								'class' => '',
								'id' => '',
							),
                        ),
                        array(
                            'key' => 'people-block-title',
                            'name' => 'title',
                            'label' => 'Title',
                            'required' => true,
							'wrapper' => array(
								'width' => '30',
								'class' => '',
								'id' => '',
							),
						),
						array(
							'key' => 'field_60e123851c6b',
							'label' => 'LinkedIn',
							'name' => 'linkedin',
							'type' => 'link',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '10',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
						),
                    )
				),
			),
			'location' => array(
				array(
					array(
						'param' => 'block',
						'operator' => '==',
						'value' => 'acf/people',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'left',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => true,
			'description' => '',
			'acfe_display_title' => '',
			'acfe_autosync' => '',
			'acfe_form' => 0,
			'acfe_meta' => '',
			'acfe_note' => '',
		));

    }
}